apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: payment
  labels:
    service: payment
    release: monitoring
spec:
  selector:
    matchLabels:
      service: payment
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
