apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: shipping
  labels:
    service: shipping
    release: monitoring
spec:
  selector:
    matchLabels:
      service: shipping
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 30s
