apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: user
  labels:
    service: user
    release: monitoring
spec:
  selector:
    matchLabels:
      service: user
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
