apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: web
  labels:
    service: web
    release: monitoring
spec:
  selector:
    matchLabels:
      service: web
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
