mongodb:
  image:
    repository: ""
    tag: ""
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 200m
      memory: 200Mi

mysql:
  image:
    repository: ""
    tag: ""
  resources:
    requests:
      cpu: 100m
      memory: 700Mi
    limits:
      cpu: 200m
      memory: 1024Mi

rabbitmq:
  image: rabbitmq:3.7-management-alpine

redis:
  image: redis:4.0.6
  storage: 1Gi
  storageClassName: gp2
