service:
  name: shipping
  port: 8080
  targetPort: 8080

resources:
  requests:
    cpu: 100m
    memory: 500Mi
  limits:
    cpu: 200m
    memory: 1000Mi

readinessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 5
  failureThreshold: 30
  successThreshold: 1

serviceMonitor:
  enabled: true
  port: http
  path: /actuator/prometheus
  interval: 30s
