{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "mavic-drone-service.name" . }}
  labels:
    {{- include "mavic-drone-service.labels" . | nindent 4 }}
    release: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mavic-drone-service.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
    - port: {{ .Values.serviceMonitor.port }}
      path: {{ .Values.serviceMonitor.path }}
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
