apiVersion: v1
kind: Service
metadata:
  name: {{ include "mavic-drone-service.name" . }}
  labels:
    {{- include "mavic-drone-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "mavic-drone-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    {{- if .Values.service.ports }}
    {{- toYaml .Values.service.ports | nindent 4 }}
    {{- else }}
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
    {{- end }}
